### ISSUE TITLE
Are the VFX generated only from the respacks?

### ISSUE THREAD

**Issue by aliabbas299792** [mon/0x40-web#70]
Hi, I'm not entirely sure on how the VFX for this stuff is achieved, is it a case of manually placed beats/image synced in the respack stuff interpreted by the frontend and then rendered via the canvas?
Or is there some algorithm which calculates the beats from the music and can generate this itself?

**Comment by mon** [comment]
Hi!

Auto-generated beats aren't good enough (a few people have tried with not amazing results). All the beats are manually placed. There are some details in the [editor docs](https://github.com/mon/0x40-web/blob/master/docs/Editor.md) on how to create your own maps, or you can hit `e` to inspect any existing map.

**Comment by aliabbas299792** [comment]
Sorry to extend this issue, would you be able to point to any of these should they be available on the web somewhere?

**Comment by mon** [comment]
The existing maps? Absolutely!

I have a few links in the README to maps that I've made that I like.  
If you look at the URL, you'll see it's custom.html with a packs argument  
You can replace that with any one of my respacks [in my respack folder](https://0x40.mon.im/respacks/?C=M;O=D)  
It's not very user-friendly, but I usually just link these on discord to people....

Otherwise, there are some charts on the Hues Portal, https://portal.0x40hu.es/

**Comment by aliabbas299792** [comment]
Hi, thanks for those, but sorry I was asking about the auto generating attempts from this
> a few people have tried with not amazing results
Would you happen to know if they are available/where these attempts are?

**Comment by mon** [comment]
Oh, that makes a bit more sense....

I don't have any specific links. Generally, it's people who have popped into the Hues IRC/Discord and said "I'm doing this", posting a video of results, and then dropping their project because the results aren't too good compared to manual mapping.
I don't recall ever seeing code posted, sorry.

**Comment by aliabbas299792** [comment]
Ah I see, understandable, thank you for your help nonetheless
